version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: symfony/serializer
    versions:
    - 4.4.19
  - dependency-name: phpunit/phpunit
    versions:
    - 8.5.14
  - dependency-name: symfony/polyfill-ctype
    versions:
    - 1.22.0
  - dependency-name: webmozart/assert
    versions:
    - 1.9.1
