version: 2

references:
  WP_ORG_PLUGIN_NAME: &WP_ORG_PLUGIN_NAME
    dation-woocommerce

  container_config: &container_config
    docker:
      - image: circleci/php:7.2
    environment:
      - WP_ORG_PLUGIN_NAME: *WP_ORG_PLUGIN_NAME
    working_directory: ~/dation-woocommerce

  workspace_root: &workspace_root
    ~/dation-woocommerce

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  install_subversion: &install_subversion
     run:
       name: Install subversion
       command: sudo apt-get install subversion

jobs:
  # Build dependencies
  build:
    <<: *container_config
    steps:
      - checkout
      - run:
          name: Install dependencies with Composer
          command: |
            set -x
            composer install --no-dev --ignore-platform-reqs --no-scripts --no-progress
      - persist_to_workspace:
          root: .
          paths:
            - vendor

  # Unit tests
  test:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - run:
          name: Install test depedencies with Composer
          command: |
            set -x
            composer install --ignore-platform-reqs --no-scripts --no-progress
      - run:
          name: Run tests
          command: |
            set -x
            ./vendor/bin/phpunit --bootstrap vendor/autoload.php tests

  # Create ZIP file for manual install
  package:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - run:
          name: Create ZIP file
          command: zip -r dation-woocommerce.zip . -x *.git* -x *.circleci* -x tests
      - store_artifacts:
          path: dation-woocommerce.zip
          destination: dation-woocommerce.zip

  # Deploy plugin to Wordpress directory
  deploy_plugin:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - *install_subversion
      - run:
          name: Deploy new version to WordPress plugin directory
          command: .circleci/deploy-plugin.sh

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - package:
          requires:
            - test
      - deploy_plugin:
          requires:
            - test
