version: 2

# This configuration is largely inspired by Carl Alexander's article
# https://carlalexander.ca/continuous-deployment-wordpress-directory-circleci/

references:
  WP_ORG_PLUGIN_NAME: &WP_ORG_PLUGIN_NAME
    dation-woocommerce

  container_config: &container_config
    docker:
      - image: circleci/php:8.0
    environment:
      - WP_ORG_PLUGIN_NAME: *WP_ORG_PLUGIN_NAME
    working_directory: ~/dation-woocommerce

  workspace_root: &workspace_root
    ~/dation-woocommerce

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  update_apt_get: &update_apt_get
    run:
      name: Update apt-get
      command: sudo apt-get update

  install_subversion: &install_subversion
     run:
       name: Install subversion
       command: sudo apt-get install subversion

jobs:
  # Build dependencies
  build:
    <<: *container_config
    steps:
      - checkout
      - run:
          name: Install dependencies with Composer
          command: |
            set -x
            composer install --no-dev --ignore-platform-reqs --no-scripts --no-progress
      - persist_to_workspace:
          root: .
          paths:
            - vendor

  # Unit tests
  test:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - run:
          name: Install test depedencies with Composer
          command: |
            set -x
            composer install --ignore-platform-reqs --no-scripts --no-progress
      - run:
          name: Run tests
          command: |
            set -x
            ./vendor/bin/phpunit --bootstrap vendor/autoload.php tests

  # Lint ALL php files
  lint_php71:
    <<: *container_config
    docker:
      - image: circleci/php:8.0
    steps:
      - checkout
      - *attach_workspace
      - run:
          name: Lint PHP files for PHP version 7.1
          command: .circleci/phplint.sh

  # Create ZIP file for manual install
  package:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - run:
          name: Create ZIP file
          command: zip -r dation-woocommerce.zip . -x *.git* -x *.circleci* -x tests
      - store_artifacts:
          path: dation-woocommerce.zip
          destination: dation-woocommerce.zip

  # Deploy plugin to Wordpress directory
  deploy_plugin:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - *update_apt_get
      - *install_subversion
      - run:
          name: Deploy new version to WordPress plugin directory
          command: .circleci/deploy-plugin.sh

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - lint_php71:
          requires:
            - build
      - package:
          requires:
            - test
            - lint_php71
# The plugin requires PHP 7.1, the Directory linter requires 7.0 syntax
      - deploy_plugin:
          filters:
            branches:
              only:
                - master
          requires:
            - test
            - lint_php71
