version: 2.1

# This configuration is largely inspired by Carl Alexander's article
# https://carlalexander.ca/continuous-deployment-wordpress-directory-circleci/

executors:
  php:
    docker:
      - image: circleci/php:8.0
    environment:
      WP_ORG_PLUGIN_NAME: dation-woocommerce
    working_directory: ~/dation-woocommerce

commands:
  update_apt_get:
    steps:
      - run:
          name: Update apt-get
          command: sudo apt-get update

  install_subversion:
    steps:
      - run:
          name: Install subversion
          command: sudo apt-get install subversion

  attach_build_workspace:
    steps:
      - attach_workspace:
          at: ~/dation-woocommerce

jobs:
  # Build dependencies
  build:
    executor: php
    steps:
      - checkout
      - run:
          name: Install dependencies with Composer
          command: |
            set -x
            composer install --no-dev --ignore-platform-reqs --no-scripts --no-progress
      - run:
          name: run strauss
          command: php -d error_reporting=E_ERROR vendor/bin/strauss
      - persist_to_workspace:
          root: .
          paths:
            - vendor
            - strauss

  # Unit tests
  test:
    executor: php
    steps:
      - checkout
      - attach_build_workspace
      - run:
          name: Install test depedencies with Composer
          command: |
            set -x
            composer install --ignore-platform-reqs --no-scripts --no-progress
      - run:
          name: Run tests
          command: |
            set -x
            ./vendor/bin/phpunit --bootstrap tests/bootstrap.php tests

  # Lint ALL php files
  lint_php71:
    executor: php
    steps:
      - checkout
      - attach_build_workspace
      - run:
          name: Lint PHP files for PHP version 7.1
          command: .circleci/phplint.sh

  # Create ZIP file for manual install
  package:
    executor: php
    steps:
      - checkout
      - attach_build_workspace
      - run:
          name: Create ZIP file
          command: |
            set -x
            .circleci/build-plugin.sh /tmp/build/dation-woocommerce
            cd /tmp/build && zip -qr ~/dation-woocommerce/dation-woocommerce.zip dation-woocommerce
      - store_artifacts:
          path: dation-woocommerce.zip
          destination: dation-woocommerce.zip

  # Deploy plugin to Wordpress directory
  deploy_plugin:
    executor: php
    steps:
      - checkout
      - attach_build_workspace
      - update_apt_get
      - install_subversion
      - run:
          name: Deploy new version to WordPress plugin directory
          command: .circleci/deploy-plugin.sh

workflows:
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - lint_php71:
          requires:
            - build
      - package:
          requires:
            - test
            - lint_php71
# The plugin requires PHP 7.1, the Directory linter requires 7.0 syntax
      - deploy_plugin:
          filters:
            branches:
              only:
                - master
          requires:
            - test
            - lint_php71