version: 2
jobs:
  # Job 'build': create zip file for install
  build:
    docker:
      - image: circleci/php:7.2
    steps:
      - checkout
      - run:
          name: Composer install
          command: |
            set -x
            composer install --ignore-platform-reqs --no-scripts --no-progress
      - run:
          name: Run tests
          command: |
            set -x
            ./vendor/bin/phpunit --bootstrap vendor/autoload.php tests
      - run:
          name: Composer remove dev libraries
          command: |
            set -x
            composer install --no-dev --ignore-platform-reqs --no-scripts --no-progress
      - run:
          name: Create ZIP file
          command: zip -r dation-woocommerce.zip . -x *.git* -x *.circleci* -x tests
      - store_artifacts:
          path: dation-woocommerce.zip
          destination: dation-woocommerce.zip