version: 2
jobs:
  # Job 'build': create zip file for install
  build:
    machine: true
    steps:
      - checkout
      - run: zip -r dation-woocommerce.zip . -x *.git*
      - store_artifact:
          path: dation-woocommerce.zip